version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "hms.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/hms'
    ports:
      - '80:80'

  celery:
    build: .
    command: celery worker -B -l info -A hms.blueprints.contact.tasks 
    env_file:
      - '.env'
    volumes:
      - '.:/hms'

volumes:
  postgres:
  redis:
